apiVersion: v2
name: lakefs
description: A Helm chart for running LakeFS on Kubernetes
type: application
version: 1.2.12
appVersion: 1.20.0

home: https://lakefs.io
icon: https://lakefs.io/wp-content/uploads/2020/07/lake-fs-color-2.svg
sources:
  - https://github.com/treeverse/lakeFS
maintainers:
  - name: treeverse
    email: services@treeverse.io
