apiVersion: v2
name: lakefs
description: A Helm chart for Kubernetes
type: application
version: 0.3.2
appVersion: 0.10.2

home: https://lakefs.io
icon: https://lakefs.io/wp-content/uploads/2020/07/lake-fs-color-2.svg
sources:
  - https://github.com/treeverse/lakeFS
maintainers:
  - name: Treeverse
    email: support@treeverse.io
