apiVersion: v2
name: lakefs
description: A Helm chart for running LakeFS on Kubernetes
type: application
version: 0.12.0
appVersion: 0.110.0

home: https://lakefs.io
icon: https://lakefs.io/wp-content/uploads/2020/07/lake-fs-color-2.svg
sources:
  - https://github.com/treeverse/lakeFS
maintainers:
  - name: treeverse
    email: services@treeverse.io
